// <auto-generated />
using System;
using HRPortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRPortal.Migrations
{
    [DbContext(typeof(PortaldbContext))]
    partial class PortaldbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("HRPortal.Models.Educationdetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Comments")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int(11)");

                    b.Property<string>("InstituteUniversity")
                        .IsRequired()
                        .HasColumnName("Institute/University")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<int>("YearOfPass")
                        .HasColumnName("yearOfPass")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasName("fk_EducationDetails_idx");

                    b.ToTable("educationdetails","portaldb");
                });

            modelBuilder.Entity("HRPortal.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Address")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("OfficePhoneNumber")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("Photo")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("WebUrl")
                        .HasColumnName("WebURL")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.HasKey("EmployeeId");

                    b.ToTable("employee","portaldb");
                });

            modelBuilder.Entity("HRPortal.Models.Employeeskills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Comments")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int(11)");

                    b.Property<string>("EmployeeSkill")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<int>("SkillRating")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasName("fk_EmployeeSkills_idx");

                    b.ToTable("employeeskills","portaldb");
                });

            modelBuilder.Entity("HRPortal.Models.Experiencedetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("EndYear")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartYear")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasName("fk_ExperienceDetails_idx");

                    b.ToTable("experiencedetails","portaldb");
                });

            modelBuilder.Entity("HRPortal.Models.Educationdetails", b =>
                {
                    b.HasOne("HRPortal.Models.Employee", "Employee")
                        .WithMany("Educationdetails")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("fk_EducationDetails")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HRPortal.Models.Employeeskills", b =>
                {
                    b.HasOne("HRPortal.Models.Employee", "Employee")
                        .WithMany("Employeeskills")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("fk_EmployeeSkills")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HRPortal.Models.Experiencedetails", b =>
                {
                    b.HasOne("HRPortal.Models.Employee", "Employee")
                        .WithMany("Experiencedetails")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("fk_ExperienceDetails")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
